//ROS typedefs
#include "ros/ros.h"
#include <brics_actuator/JointVelocities.h>

/* protected region user include files on begin */
/* protected region user include files end */

class torso_test_config
{
public:

};

class torso_test_data
{
// autogenerated: don't touch this class
public:
//input data
  
	
//output data
    	brics_actuator::JointVelocities out_command_vel;
 

};

class torso_test_impl
{
	/* protected region user member variables on begin */
	/* protected region user member variables end */

public:
    torso_test_impl() 
    {
        /* protected region user constructor on begin */
		/* protected region user constructor end */
    }
    void configure(torso_test_config config) 
    {
        /* protected region user configure on begin */
		/* protected region user configure end */
    }
    void update(torso_test_data &data, torso_test_config config)
    {
        /* protected region user update on begin */
    	brics_actuator::JointVelocities empty; //TODO@BRIDE: out_ variables should be empty at begin of update(?)
    	data.out_command_vel = empty;

    	ros::Time time_stamp = ros::Time::now();
    	for (int i = 0; i < 3; i++)
    	{
    		brics_actuator::JointValue joint_value;
    		joint_value.timeStamp = time_stamp;
    		joint_value.joint_uri = "joint_xxx";
    		joint_value.unit = "rad/s";
    		joint_value.value = 1.0;
    		data.out_command_vel.velocities.push_back(joint_value);
    	}
		/* protected region user update end */
    }

    


    
    /* protected region user additional functions on begin */
	/* protected region user additional functions end */
    
};
